apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name:  {{ include "targilArgo.fullname" . | default "targil" | quote  }}
  labels:
    {{ include "targilArgo" . | nindent 4 }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      {{ include "targilArgo.selectorLabels" . | nindent 6 }}   
    spec:
      containers:
      - image: "{{ .Values.mysql.image.name }}:{{ .Values.mysql.image.tag }}"
        imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
        name: {{ "mySQL" }}
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: {{ .Values.mysql.mysqlRootPassword }}
         - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: {{ .Values.mysql.mysqlRootPassword }}
         - name: MYSQL_USER
          value: {{ .Values.mysql.mysqlRootPassword }}
         - name: MYSQL_PASSWORD
          value: {{ .Values.mysql.mysqlRootPassword }}
         - name: MYSQL_DATABASE
          value: {{ .Values.mysql.mysqlRootPassword }}    
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      