apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "targil_argo.fullname" . | default "targil" | quote  }}
  labels:
    {{ include "targil_argo" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "targil_argo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "targil_argo.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "targil_argo.serviceAccountName" .  }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
