apiVersion: v1
kind: Service
metadata:
  name: {{ include "targilArgo.fullname" . | default "targil" | quote }}
  labels:  
  {{ include "targilArgo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: node
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    {{ include "targilArgo.selectorLabels" . | nindent 4 }}
